In [1]:
import numpy as np

In [2]:
data0axis = np.arange(0,20000)

In [3]:
data0axis

array([    0,     1,     2, ..., 19997, 19998, 19999])

In [4]:
data = np.zeros((20000,2))

In [5]:
data.shape

(20000, 2)

In [6]:
data[:,0] = data0axis

In [7]:
data

array([[0.0000e+00, 0.0000e+00],
       [1.0000e+00, 0.0000e+00],
       [2.0000e+00, 0.0000e+00],
       ...,
       [1.9997e+04, 0.0000e+00],
       [1.9998e+04, 0.0000e+00],
       [1.9999e+04, 0.0000e+00]])

In [38]:
def generator(data, lookback, delay, min_index, max_index,
              shuffle=False, batch_size=128, step=6):
    if max_index is None:
        max_index = len(data) - delay - 1
    i = min_index + lookback
    while 1:
        if shuffle:
            rows = np.random.randint(
                min_index + lookback, max_index, size=batch_size)
            #生成闭区间[low,high]上离散均匀分布的整数值 (min_index + lookback和max_index間，
            """size:Output shape. If the given shape is, e.g., (m, n, k),
            then m * n * k samples are drawn. Default is None,
            in which case a single value is returned."""
        else:
            if i + batch_size >= max_index:
                i = min_index + lookback
            rows = np.arange(i, min(i + batch_size, max_index))
            """
            arange([start,] stop[, step,], dtype=None)
            根据start与stop指定的范围以及step设定的步长，生成一个 ndarray。
              >>> np.arange(3)
                array([0, 1, 2])
                >>> np.arange(3.0)
                array([ 0.,  1.,  2.])
                >>> np.arange(3,7)
                array([3, 4, 5, 6])
                >>> np.arange(3,7,2)
                array([3, 5])
            """
            i += len(rows)
                
        samples = np.zeros((len(rows),lookback // step,data.shape[-1]))
        targets = np.zeros((len(rows),))
        for j, row in enumerate(rows):
            indices = range(rows[j] - lookback, rows[j], step)
            samples[j] = data[indices]
            targets[j] = data[rows[j] + delay][1]
        yield samples, targets

In [71]:
def formulate(data, lookback, delay, min_index, max_index,
              shuffle=False, batch_size=128, step=6):
    if max_index is None:
        max_index = len(data) - delay - 1
    i = min_index + lookback
    while 1:
        if shuffle:
            rows = np.random.randint(
                min_index + lookback, max_index, size=batch_size)
            #生成闭区间[low,high]上离散均匀分布的整数值 (min_index + lookback和max_index間，
            """size:Output shape. If the given shape is, e.g., (m, n, k),
            then m * n * k samples are drawn. Default is None,
            in which case a single value is returned."""
        else:
            if i + batch_size >= max_index:
                i = min_index + lookback
            rows = np.arange(i, min(i + batch_size, max_index))
            """
            arange([start,] stop[, step,], dtype=None)
            根据start与stop指定的范围以及step设定的步长，生成一个 ndarray。
              >>> np.arange(3)
                array([0, 1, 2])
                >>> np.arange(3.0)
                array([ 0.,  1.,  2.])
                >>> np.arange(3,7)
                array([3, 4, 5, 6])
                >>> np.arange(3,7,2)
                array([3, 5])
            """
            print("i is",i)
            print("row is ",rows)
            i += len(rows)
                
        samples = np.zeros((len(rows),lookback // step,data.shape[-1]))
        targets = np.zeros((len(rows),))
        for j, row in enumerate(rows):
            #j是rows裡最小排到最大的index
            indices = range(rows[j] - lookback, rows[j], step)
            #indices是一個range出的list
            samples[j] = data[indices]
            #所以sample[j]是一串序列，所以samples是很多串序列
            targets[j] = data[rows[j] + delay][1]
        return samples, targets

In [72]:
lookback = 720
step = 6
delay = 144
batch_size = 128

In [73]:
test_1 = formulate(data,
                    lookback=lookback,
                    delay=delay,
                    min_index=0,
                    max_index=10000,
                    shuffle=True,
                    step=step,
                    batch_size=batch_size)

In [74]:
test_1[0].shape

(128, 120, 2)

In [75]:
test_1[0][0:3]

array([[[ 688.,    0.],
        [ 694.,    0.],
        [ 700.,    0.],
        [ 706.,    0.],
        [ 712.,    0.],
        [ 718.,    0.],
        [ 724.,    0.],
        [ 730.,    0.],
        [ 736.,    0.],
        [ 742.,    0.],
        [ 748.,    0.],
        [ 754.,    0.],
        [ 760.,    0.],
        [ 766.,    0.],
        [ 772.,    0.],
        [ 778.,    0.],
        [ 784.,    0.],
        [ 790.,    0.],
        [ 796.,    0.],
        [ 802.,    0.],
        [ 808.,    0.],
        [ 814.,    0.],
        [ 820.,    0.],
        [ 826.,    0.],
        [ 832.,    0.],
        [ 838.,    0.],
        [ 844.,    0.],
        [ 850.,    0.],
        [ 856.,    0.],
        [ 862.,    0.],
        [ 868.,    0.],
        [ 874.,    0.],
        [ 880.,    0.],
        [ 886.,    0.],
        [ 892.,    0.],
        [ 898.,    0.],
        [ 904.,    0.],
        [ 910.,    0.],
        [ 916.,    0.],
        [ 922.,    0.],
        [ 928.,    0.],
        [ 934., 

In [76]:
test_2 = formulate(data,
                    lookback=lookback,
                    delay=delay,
                    min_index=0,
                    max_index=10000,
                    step=step,
                    batch_size=batch_size)
#i不會iterate，row基本上就是i~i+batch size，或到max index
#這裡rows長度是127

i is 720
row is  [720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847]


In [69]:
test_2[0][0:3]

array([[[  0.,   0.],
        [  6.,   0.],
        [ 12.,   0.],
        [ 18.,   0.],
        [ 24.,   0.],
        [ 30.,   0.],
        [ 36.,   0.],
        [ 42.,   0.],
        [ 48.,   0.],
        [ 54.,   0.],
        [ 60.,   0.],
        [ 66.,   0.],
        [ 72.,   0.],
        [ 78.,   0.],
        [ 84.,   0.],
        [ 90.,   0.],
        [ 96.,   0.],
        [102.,   0.],
        [108.,   0.],
        [114.,   0.],
        [120.,   0.],
        [126.,   0.],
        [132.,   0.],
        [138.,   0.],
        [144.,   0.],
        [150.,   0.],
        [156.,   0.],
        [162.,   0.],
        [168.,   0.],
        [174.,   0.],
        [180.,   0.],
        [186.,   0.],
        [192.,   0.],
        [198.,   0.],
        [204.,   0.],
        [210.,   0.],
        [216.,   0.],
        [222.,   0.],
        [228.,   0.],
        [234.,   0.],
        [240.,   0.],
        [246.,   0.],
        [252.,   0.],
        [258.,   0.],
        [264.,   0.],
        [2

In [70]:
test_2[0][10:13]

array([[[ 10.,   0.],
        [ 16.,   0.],
        [ 22.,   0.],
        [ 28.,   0.],
        [ 34.,   0.],
        [ 40.,   0.],
        [ 46.,   0.],
        [ 52.,   0.],
        [ 58.,   0.],
        [ 64.,   0.],
        [ 70.,   0.],
        [ 76.,   0.],
        [ 82.,   0.],
        [ 88.,   0.],
        [ 94.,   0.],
        [100.,   0.],
        [106.,   0.],
        [112.,   0.],
        [118.,   0.],
        [124.,   0.],
        [130.,   0.],
        [136.,   0.],
        [142.,   0.],
        [148.,   0.],
        [154.,   0.],
        [160.,   0.],
        [166.,   0.],
        [172.,   0.],
        [178.,   0.],
        [184.,   0.],
        [190.,   0.],
        [196.,   0.],
        [202.,   0.],
        [208.,   0.],
        [214.,   0.],
        [220.,   0.],
        [226.,   0.],
        [232.,   0.],
        [238.,   0.],
        [244.,   0.],
        [250.,   0.],
        [256.,   0.],
        [262.,   0.],
        [268.,   0.],
        [274.,   0.],
        [2

In [85]:
test_2[0][120:130]

array([[[120.,   0.],
        [126.,   0.],
        [132.,   0.],
        ...,
        [822.,   0.],
        [828.,   0.],
        [834.,   0.]],

       [[121.,   0.],
        [127.,   0.],
        [133.,   0.],
        ...,
        [823.,   0.],
        [829.,   0.],
        [835.,   0.]],

       [[122.,   0.],
        [128.,   0.],
        [134.,   0.],
        ...,
        [824.,   0.],
        [830.,   0.],
        [836.,   0.]],

       ...,

       [[125.,   0.],
        [131.,   0.],
        [137.,   0.],
        ...,
        [827.,   0.],
        [833.,   0.],
        [839.,   0.]],

       [[126.,   0.],
        [132.,   0.],
        [138.,   0.],
        ...,
        [828.,   0.],
        [834.,   0.],
        [840.,   0.]],

       [[127.,   0.],
        [133.,   0.],
        [139.,   0.],
        ...,
        [829.,   0.],
        [835.,   0.],
        [841.,   0.]]])

In [ ]:
test_3 = formulate(data,
                    lookback=lookback,
                    delay=delay,
                    min_index=10000,
                    max_index=15000,
                    step=step,
                    batch_size=batch_size)