In [4]:
def formulate(a):
    while 1:
        b=a+1
        return(b)

In [5]:
a = formulate(2)
print(a)

3


In [6]:
def formulate(data, lookback, delay, min_index, max_index,
              shuffle=False, batch_size=128, step=6):
    if max_index is None:
        max_index = len(data) - delay - 1
    i = min_index + lookback
    while 1:
        if shuffle:
            rows = np.random.randint(
                min_index + lookback, max_index, size=batch_size)
            #生成闭区间[low,high]上离散均匀分布的整数值 (min_index + lookback和max_index間，
            """size:Output shape. If the given shape is, e.g., (m, n, k),
            then m * n * k samples are drawn. Default is None,
            in which case a single value is returned."""
        else:
            if i + batch_size >= max_index:
                i = min_index + lookback
            rows = np.arange(i, min(i + batch_size, max_index))
            """
            arange([start,] stop[, step,], dtype=None)
            根据start与stop指定的范围以及step设定的步长，生成一个 ndarray。
              >>> np.arange(3)
                array([0, 1, 2])
                >>> np.arange(3.0)
                array([ 0.,  1.,  2.])
                >>> np.arange(3,7)
                array([3, 4, 5, 6])
                >>> np.arange(3,7,2)
                array([3, 5])
            """
            
            i += len(rows)
                
        samples = np.zeros((len(rows),lookback // step,data.shape[-1]))
        targets = np.zeros((len(rows),))
        for j, row in enumerate(rows):
            indices = range(rows[j] - lookback, rows[j], step)
            samples[j] = data[indices]
            targets[j] = data[rows[j] + delay][1]
        return samples, targets

In [7]:
lookback = 720
step = 6
delay = 144
batch_size = 128

In [8]:
test_1 = formulate(data,
                    lookback=lookback,
                    delay=delay,
                    min_index=0,
                    max_index=20000,
                    shuffle=True,
                    step=step,
                    batch_size=batch_size)

NameError: name 'data' is not defined

In [9]:
test_1[0].shape

NameError: name 'test_1' is not defined